### ISSUE TITLE
Hound CI config isn't working

### ISSUE THREAD

**Issue by tomscholz** [tomscholz/material#12]
The CI does not respect the provided config. I have disabled hound for now, but if anyone has intrest in making a PR go ahead :-)

**Comment by mileswilson** [comment]
I'd like to take a look at this - hound isn't something I've used before, but definitely looks like something I'd want to use in the future. 

I've got it picking up and linting on my fork, but I can see it's not obeying the .stylelintrc, so I'll see if I can get it working correctly, then raise a PR?

**Comment by tomscholz** [comment]
Sure :)

**Comment by tomscholz** [comment]
I guess it is not stylelints nor hounds vault. I guess I just configured something wrong. If you get it working, I would love to see a PR :-)
